### ISSUE TITLE
SPGo No longer prompting for authentication

### ISSUE THREAD

**Issue by Loevbo** [readysitego/spgo#30]
For some reason, SPGo doesn't seem to prom me for authentication anymore.

I'm using version 1.2.1:

I've tried:

- Removing and installing SPGo.
- Removing and installing Version 1.2.0
- Updated Visual Studio Code to the newest version.

**Comment by sg-chrishasz** [comment]
Hello @Loevbo 

Thank you for reporting this issue, there was a bug in SPGo 1.2.1 which caused it to load incorrectly for all users due to how NPM handles transient dependencies. I have just pushed SPGo 1.2.2 to the marketplace with a fix. Please update SPGo and reopen this issue if the bug persists.

Thanks,
Chris
