### ISSUE TITLE
Unable to download Remote folder

### ISSUE THREAD

**Issue by lafayetteduarte** [readysitego/spgo#41]
Hello,
I´m using SPGO v1.2.4 on VSCode v1.23.1 2018-05-10
my SPGO.json contains:

{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://sp69.domain.corp:9998",
    "publishingScope": "Major",
    "publishWorkspaceGlobPattern": "/**/*.min.*",
    "remoteFolders": [
        "/Style Library/",
        "/_catalogs/masterpage/"
    ]
}

When i use populate local workspace command on SPGO , the _catalogs folder gets downloaded .
Nothing from "/Style Library/" gets downloaded.

Console logs the following info:
Successfully downloaded 0 files to: src/Style Library/
Successfully downloaded 81 files to: src/_catalogs/masterpage/

Can you help me find the cause for this behaviour?
Thank you

**Comment by sg-chrishasz** [comment]
Hello @lafayetteduarte !

Since build 1.2.0, as a side-effect of Glob support, all entries in the `publishWorkspaceGlobPattern` and `remoteFolders` properties are treated Glob patterns, where previously it was assumed that a user would download all subfiles and folders.

In order to recursively download all subfolders and files, you need to use the following pattern: `/<folder>/**/*`

Here is an updated SPGo.json config which should solve your issue. _note: I've also tweaked the entry for_ `publishWorkspaceGlobPattern` _to better support uploading minified files._

```JSON
{
"sourceDirectory": "src",
"sharePointSiteUrl": "https://sp69.domain.corp:9998",
"publishingScope": "Major",
"publishWorkspaceGlobPattern": "/**/*.min.*",
"remoteFolders": [
"/Style Library/**/*",
"/_catalogs/masterpage/"
]
}
``` 

Please let me know if you still see any issues, otherwise I will close this issue.

**Comment by lafayetteduarte** [comment]
@sg-chrishasz , 
Thank you ! working perfectly.
