### ISSUE TITLE
remotefolder is not created, when only using one

### ISSUE THREAD

**Issue by ulrichbojko** [readysitego/spgo#7]
If i setup the SPGo.json like this:
{
    "sourceDirectory": "src",
    "workspaceRoot": "c:\\CodeProjects\\myproject\\",
    "sharePointSiteUrl": "https://domain.sharepoint.com",
    "publishingScope": "SaveOnly",
    "remoteFolders": [
        "/SiteAssets/"
    ]
}

The result will be that SPGo downloads the content of the SiteAssets folder into the "src" folder. Then upload or publishing will not work. 

The same goes if you add 2 folders:
"remoteFolders": [
        "/SiteAssets/",
        "/Style%20Library/"
    ]

The last folder will download into the "src" folder.

**Comment by sg-chrishasz** [comment]
Hey @ulrichbojko,  I think I know what the issue is: Can you remove the trailing slash from the workspaceRoot value, reloading VSCode and see if the error persists?

Your config should look something like this:
`{
"sourceDirectory": "src",
"workspaceRoot": "c:\CodeProjects\myproject",
"sharePointSiteUrl": "https://domain.sharepoint.com",
"publishingScope": "SaveOnly",
"remoteFolders": [
"/SiteAssets/"
]
}`

I'll harden the config manager for 0.10.1 to catch errors like this. I'm also thinking of removing the "workspaceRoot" node, as it does not really serve any value (VSCode already vends the current workspace path, and coupling the workspace URL to your local environment will break team/source integration)

Thanks for using SPGo!
